- name: Generate Prometheus config from template
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ project_base_dir }}/monitoring/prometheus.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0640'
  become: true
  notify: restart monitoring stack

- name: Start Monitoring stack with Docker Compose V2
  community.docker.docker_compose_v2:
    project_src: "{{ project_base_dir }}/monitoring"
    state: present
    pull: always
    wait: true
  become: true