project_base_dir: "{{ ansible_facts['env']['HOME'] }}/infrastructure-dev"

ssl_certs:
  - domain: danbesy.com
    provider: cloudflare
    cert_name: cert.pem
    key_name: key.pem
  - domain: danbesy.com
    provider: letsencrypt
    cert_name: fullchain.pem
    key_name: key.pem
  - domain: danbesy.lol
    provider: cloudflare
    cert_name: cert.pem
    key_name: key.pem

main_domain_name: "danbesy.com"
short_domain_name: "danbesy.lol"

ports:
  grafana: 23000
  prometheus: 29090
  node_exporter: 29100
  cadvisor: 28080

  panel: 9090
  website: 8888
  vpn_webpanel: 8338
  mail_webpanel: 4884
  matrix: 8008

domains:
  grafana: "dev-grafana.{{ main_domain_name }}"
  reviews: "dev-reviews.{{ main_domain_name }}"
  panel: "dev-panel.{{ main_domain_name }}"
  website: "dev.{{ main_domain_name }}"
  vpn_webpanel: "dev-vpn.{{ main_domain_name }}"
  mail_webpanel: "dev-mail.{{ main_domain_name }}"
  matrix: "dev-matrix.{{ main_domain_name }}"
  tg_redirect_com: "dev-tg.{{ main_domain_name }}"
  tg_redirect_lol: "dev-tg.{{ short_domain_name }}"
