project_base_dir: "{{ ansible_facts['env']['HOME'] }}/infrastructure-dev"

ssl_certs:
  - domain: danbesy.com
    provider: cloudflare
    cert_name: cert.pem
    key_name: key.pem
  - domain: danbesy.com
    provider: letsencrypt
    cert_name: fullchain.pem
    key_name: key.pem
  - domain: danbesy.lol
    provider: cloudflare
    cert_name: cert.pem
    key_name: key.pem

main_domain_name: "danbesy.com"
short_domain_name: "danbesy.lol"

ports:
  grafana: 23000
  prometheus: 29090
  node_exporter: 29100
  cadvisor: 28080

  mtproto_proxy: 2443
  website: 28888

  caddy: 25050
  panel: 29090
  vpn_webpanel: 28338
  mail_webpanel: 24884
  matrix: 28008

domains:
  grafana: "dev-grafana.{{ main_domain_name }}"
  website: "dev.{{ main_domain_name }}"
  caddy: "dev-cloud.{{ main_domain_name }}"
  panel: "dev-panel.{{ main_domain_name }}"
  reviews: "dev-reviews.{{ main_domain_name }}"
  vpn_webpanel: "dev-vpn.{{ main_domain_name }}"
  mail_webpanel: "dev-mail.{{ main_domain_name }}"
  matrix: "dev-matrix.{{ main_domain_name }}"
  tg_redirect_com: "dev-tg.{{ main_domain_name }}"
  tg_redirect_lol: "dev-tg.{{ short_domain_name }}"

images:
  grafana: "grafana/grafana-oss:13.0.1"
  prometheus: "prom/prometheus:v3.11.3"
  node_exporter: "prom/node-exporter:v1"
  cadvisor: "gcr.io/cadvisor/cadvisor:v0.55.1"

  mail_stalwart: "stalwartlabs/stalwart:v0.16.3"

  matrix_dendrite: "matrixdotorg/dendrite-monolith:v0.15.2"
  matrix_postgres: "postgres:15-alpine"

  mtproto_proxy: "telegrammessenger/proxy:2.0beta"

  nginx: "nginx:stable-alpine3.23"
  website: "danbesy/website:latest"

  caddy: "caddy:2.11.3-alpine"