- name: restart infrastructure orchestration
  community.docker.docker_compose_v2:
    project_src: "{{ project_base_dir }}"
    files:
      - "infrastructure.yaml"
    state: restarted
  become: true