project_base_dir: "{{ ansible_facts['env']['HOME'] }}/infrastructure"

ssl_certs:
  - domain: danbesy.com
    provider: cloudflare
    cert_name: cert.pem
    key_name: key.pem
  - domain: danbesy.com
    provider: letsencrypt
    cert_name: fullchain.pem
    key_name: key.pem
  - domain: danbesy.lol
    provider: cloudflare
    cert_name: cert.pem
    key_name: key.pem

main_domain_name: "danbesy.com"
short_domain_name: "danbesy.lol"

ports:
  grafana: 13000
  prometheus: 19090
  node_exporter: 19100
  cadvisor: 18080

  mtproto_proxy: 1443
  website: 18888

  caddy: 15050
  panel: 19090
  vpn_webpanel: 18338
  mail_webpanel: 14884
  matrix: 18008

  vpn_main: 3883
  vpn_alt: 8443

domains:
  grafana: "grafana.{{ main_domain_name }}"
  mtproto_proxy: "proxy.{{ main_domain_name }}"
  website: "{{ main_domain_name }}"
  caddy: "cloud.{{ main_domain_name }}"
  panel: "panel.{{ main_domain_name }}"
  reviews: "reviews.{{ main_domain_name }}"
  vpn_webpanel: "vpn.{{ main_domain_name }}"
  mail_webpanel: "mail.{{ main_domain_name }}"
  matrix: "matrix.{{ main_domain_name }}"
  tg_redirect_com: "tg.{{ main_domain_name }}"
  tg_redirect_lol: "tg.{{ short_domain_name }}"

images:
  grafana: "grafana/grafana-oss:13.0.1"
  prometheus: "prom/prometheus:v3.11.3"
  node_exporter: "prom/node-exporter:v1"
  cadvisor: "gcr.io/cadvisor/cadvisor:v0.55.1"

  mail_stalwart: "stalwartlabs/stalwart:v0.16.3"

  matrix_dendrite: "matrixdotorg/dendrite-monolith:v0.15.2"
  matrix_postgres: "postgres:15-alpine"

  mtproto_proxy: "telegrammessenger/proxy:2.0beta"

  nginx: "nginx:stable-alpine3.23"
  website: "danbesy/website:latest"

  caddy: "caddy:2.11.3-alpine"