- name: Clone infrastructure repository
  ansible.builtin.git:
    repo: "{{ repo }}"
    dest: "{{ project_base_dir }}"
    version: "{{ git_version | default('main') }}"
    force: yes
    update: yes
    recursive: yes
  become: false