services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # certs
      - ./certs:/etc/nginx/certs:ro

      # main config
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

      # snippets
      - ./cloudflare.conf:/etc/nginx/snippets/cloudflare.conf:ro
      - ./ssl.conf:/etc/nginx/snippets/ssl.conf:ro
      - ./security-headers.conf:/etc/nginx/snippets/security-headers.conf:ro
      - ./letsencrypt.conf:/etc/nginx/snippets/letsencrypt.conf:ro
      - ./whitelist.conf:/etc/nginx/snippets/whitelist.conf:ro
      - ./proxy_params.conf:/etc/nginx/snippets/proxy_params.conf:ro
      - ./proxy_ws.conf:/etc/nginx/snippets/proxy_ws.conf:ro
      - ./matrix.conf:/etc/nginx/snippets/matrix.conf:ro

      # static content
      - ./reviews/:/var/www/reviews:ro
    networks:
      proxy-network:
        ipv4_address: 172.25.0.100
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  proxy-network:
    name: proxy-network
    external: true