services:
  stalwart-mail:
    image: stalwartlabs/stalwart:v0.16.3
    container_name: stalwart-mail
    restart: unless-stopped
    ports:
      - "25:25"
      - "465:465"
      - "993:993"
    volumes:
      - ./stalwart_config:/etc/stalwart
      - ./stalwart_data:/var/lib/stalwart
    networks:
      proxy-network:
        ipv4_address: 172.20.0.10
      mail-network:
        ipv4_address: 172.24.0.10

networks:
  proxy-network:
    name: proxy-network
    external: true
  mail-network:
    name: mail-network
    external: true