- name: Generate MTProto-Proxy docker-compose from template
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ project_base_dir }}/mtproto-proxy/docker-compose.yaml"
    mode: '0644'
  become: true
  notify: restart mtproto-proxy stack

- name: Start MTProto-Proxy stack with Docker Compose V2
  community.docker.docker_compose_v2:
    project_src: "{{ project_base_dir }}/mtproto-proxy"
    state: present
    pull: always
    wait: false
  become: true